[package]
name = "virtual-computing-environment"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15", default-features = false, features = ["bevy_asset", "bevy_core_pipeline", "bevy_pbr", "bevy_render", "bevy_scene", "bevy_sprite", "bevy_text", "bevy_ui", "bevy_winit", "default_font", "x11"] }
bevy_rapier3d = { version = "0.28", features = ["simd-stable"] }
rapier3d = { version = "0.22", features = ["simd-stable"] }

[[bin]]
name = "vce"
path = "src/main.rs"